USE DATABASE CUSTOMER_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE CUSTOMERS_CLEAN AS

SELECT
    ID,
    UPPER(NAME) AS NAME,
    USERNAME,
    LOWER(EMAIL) AS EMAIL,
    WEBSITE
FROM CUSTOMER_DB.RAW.CUSTOMER_RAW;