USE DATABASE CUSTOMER_DB;

-- ============================================
-- Bronze → Silver
-- ============================================

TRUNCATE TABLE CUSTOMER_DB.SILVER.CUSTOMER_CLEAN;

INSERT INTO CUSTOMER_DB.SILVER.CUSTOMER_CLEAN
(
    ID,
    NAME,
    USERNAME,
    EMAIL,
    PHONE,
    WEBSITE,
    LOAD_TIMESTAMP
)

SELECT DISTINCT
    ID,
    TRIM(UPPER(NAME)) AS NAME,
    TRIM(USERNAME) AS USERNAME,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    TRIM(PHONE) AS PHONE,
    LOWER(TRIM(WEBSITE)) AS WEBSITE,
    LOAD_TIMESTAMP

FROM CUSTOMER_DB.BRONZE.CUSTOMER_RAW

WHERE EMAIL IS NOT NULL;

-- ============================================
-- Silver → Gold
-- ============================================

TRUNCATE TABLE CUSTOMER_DB.GOLD.CUSTOMER_ANALYTICS;

INSERT INTO CUSTOMER_DB.GOLD.CUSTOMER_ANALYTICS
(
    ID,
    NAME,
    EMAIL,
    WEBSITE,
    LOAD_TIMESTAMP,
    EMAIL_PROVIDER
)

SELECT
    ID,
    NAME,
    EMAIL,
    WEBSITE,
    LOAD_TIMESTAMP,
    SPLIT_PART(EMAIL, '@', 2) AS EMAIL_PROVIDER

FROM CUSTOMER_DB.SILVER.CUSTOMER_CLEAN;